site_name: Lumino
nav:
  - Home: index.md
  - Introducción: introduction.md
  - Requisitos del proyecto: requirements.md
  - Diseño del Sistema: design.md
  - Implementación: implementation.md
  - Pruebas: test.md
  - Despliegue: deployment.md
  - Manuales de usuario: user_manual.md
  - Mantenimiento y actualización: support.md
  - Conclusión y futuro: conclusion.md
theme: readthedocs
